@Milliken.API_HostAddress = http://localhost:5217

PUT {{Milliken.API_HostAddress}}/GetBooks/
Accept: application/json

###
PUT {{Milliken.API_HostAddress}}/GetEBooks/
Accept: application/json

###
PUT {{Milliken.API_HostAddress}}/TotalNumberOfAllBooks/
Accept: application/json

###
DELETE {{Milliken.API_HostAddress}}/DeleteBook/
Accept: application/json

###
POST {{Milliken.API_HostAddress}}/AddBook/
Accept: application/json

###
POST {{Milliken.API_HostAddress}}/AddEBook/
Accept: application/json

###
